version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hr-chatbot-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - GROQ_API_KEY=your_api_key

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hr-chatbot-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
